### ISSUE TITLE
Python Codes For Chapter 8 

### ISSUE THREAD

**Issue by davidmontgom** [Pat-Laub/hawkesbook#1]
Hi,

Do you have python code for Chapter 8 Algo 6 the MCMC MH.  If it can be added to repo then great

**Comment by Pat-Laub** [comment]
Hi David,

Here is a version of code we used to created the Figure 8.1 plots: https://gist.github.com/Pat-Laub/d15c5217e9f36b84e1e4d185b532490a
This notebook shows a smaller MCMC run than we used for the book (this one took an hour to run on my machine just now), so the histograms won't be identical..

Hope this helps!

Regards, Patrick

**Comment by davidmontgom** [comment]
Thanks!!!! FYI Love the book its a treasured book in my collection and you
et al aced it with a clear mapping of theory to code and should be set as
an example from theory to code.

See Ya

**Comment by Pat-Laub** [comment]
Thanks very much for your kind words David! :)
I'm glad that our many evenings & weekends working on the book were not in vain haha.
